
good_weather = [
    "Fair",
    "Clear",
    "Mostly Cloudy",
    "Partly Cloudy",
    "Scattered Clouds",
    "Fair / Windy",
    "Mostly Cloudy / Windy",
    "Partly Cloudy / Windy"
]

neutral_weather = [
    "Cloudy",
    "Overcast",
    "NULL/MISSING",
    "Haze",
    "Fog",
    "Cloudy / Windy",
    "Smoke",
    "N/A Precipitation",
    "Mist",
    "Fog / Windy",
    "Patches of Fog",
    "Shallow Fog",
    "Haze / Windy",
    "Smoke / Windy",
    "Partial Fog",
    "Light Haze",
    "Mist / Windy",
    "Light Fog",
    "Patches of Fog / Windy",
    "Shallow Fog / Windy",
    "Heavy Fog",
    "Heavy Smoke",
    "Light Smoke"
]

bad_weather = [
    "Light Snow",
    "Light Rain",
    "Snow",
    "Rain",
    "Heavy Snow",
    "Heavy Rain",
    "Light Drizzle",
    "Light Snow / Windy",
    "Wintry Mix",
    "T-Storm",
    "Thunder in the Vicinity",
    "Light Rain with Thunder",
    "Thunder",
    "Light Freezing Rain",
    "Heavy T-Storm",
    "Light Thunderstorms and Rain",
    "Thunderstorm",
    "Light Rain / Windy",
    "Heavy Thunderstorms and Rain",
    "Snow / Windy",
    "Light Freezing Fog",
    "Thunderstorms and Rain",
    "Drizzle",
    "Heavy Snow / Windy",
    "Blowing Snow",
    "Heavy T-Storm / Windy",
    "Light Freezing Drizzle",
    "Rain / Windy",
    "Snow and Sleet",
    "T-Storm / Windy",
    "Showers in the Vicinity",
    "Heavy Rain / Windy",
    "Light Ice Pellets",
    "Thunder / Windy",
    "Light Snow and Sleet",
    "Blowing Snow / Windy",
    "Wintry Mix / Windy",
    "Sleet",
    "Ice Pellets",
    "Light Sleet",
    "Heavy Drizzle",
    "Snow and Sleet / Windy",
    "Freezing Rain",
    "Drizzle and Fog",
    "Light Rain Showers",
    "Light Drizzle / Windy",
    "Light Snow with Thunder",
    "Widespread Dust",
    "Light Freezing Rain / Windy",
    "Light Rain Shower",
    "Light Snow and Sleet / Windy",
    "Light Snow Showers",
    "Blowing Dust / Windy",
    "Heavy Sleet",
    "Rain Showers",
    "Light Thunderstorms and Snow",
    "Freezing Rain / Windy",
    "Sleet / Windy",
    "Heavy Blowing Snow",
    "Thunder / Wintry Mix",
    "Squalls",
    "Heavy Snow with Thunder",
    "Heavy Ice Pellets",
    "Small Hail",
    "Blowing Dust",
    "Heavy Thunderstorms and Snow",
    "Light Sleet / Windy",
    "Sleet and Thunder",
    "Rain Shower",
    "Hail",
    "Snow Showers",
    "Heavy Freezing Drizzle",
    "Snow and Thunder",
    "Sand / Dust Whirlwinds",
    "Light Snow Shower",
    "Freezing Drizzle",
    "Heavy Freezing Rain",
    "Funnel Cloud",
    "Squalls / Windy",
    "Snow and Thunder / Windy",
    "Heavy Sleet and Thunder",
    "Thunderstorms and Snow",
    "Heavy Sleet / Windy",
    "Low Drifting Snow",
    "Light Blowing Snow",
    "Drizzle / Windy",
    "Light Hail",
    "Thunder and Hail",
    "Thunderstorms and Ice Pellets",
    "Light Sleet and Thunder",
    "Sand",
    "Light Snow Grains",
    "Heavy Rain Showers",
    "Light Rain Shower / Windy",
    "Heavy Rain Shower",
    "Heavy Thunderstorms with Ice Pellets",
    "Snow Shower",
    "Volcanic Ash",
    "Thunder and Hail / Windy",
    "Sandstorm",
    "Drifting Snow",
    "Light Snow Shower / Windy",
    "Widespread Dust / Windy",
    "Heavy Thunderstorms with Hail",
    "Thunder / Wintry Mix / Windy",
    "Rain / Freezing Rain",
    "Tornado",
    "Sand / Dust Whirls Nearby",
    "Light Thunderstorm",
    "Light Snow Grains / Windy",
    "Heavy Snow Showers",
    "Light Thunderstorms and Ice Pellets",
    "Light Ice Pellet Showers",
    "Heavy Thunderstorm",
    "Heavy Thunderstorms with Small Hail",
    "Dust Whirls",
    "Rain Shower / Windy",
    "Rain and Sleet",
    "Blowing Snow Nearby / Windy",
    "Snow Grains",
    "Thunder and Small Hail",
    "Blowing Snow Nearby",
    "Light Thunderstorms with Small Hail",
    "Rain and Snow / Windy",
    "Blowing Sand",
    "Sand / Dust Whirlwinds / Windy",
    "Sleet and Thunder / Windy",
    "Rain and Snow",
    "Drizzle and Fog / Windy",
    "Duststorm / Windy",
    "Hail / Windy",
    "Heavy Hail",
    "Small Hail / Windy",
    "Heavy Drizzle / Windy",
    "Ice Crystals",
    "Thunderstorms with Hail",
    "Light Thunderstorms with Hail",
    "Low Drifting Sand / Windy",
    "Drifting Snow / Windy",
    "Snow Shower / Windy",
    "Blowing Sand / Windy",
    "Thunderstorms with Small Hail",
    "Low Drifting Dust / Windy"
]
